### ISSUE TITLE
Team Beathoven - :musical_keyboard: 

### ISSUE THREAD

**Issue by Ruturajn** [ese-detkin-lab/ese5190-2022#318]
**Tasks:**
 
- [x] Create an array containing the PWM duty cycles that will simulate an audio note.
- [x] Get a single *Tabla* note to play on a speaker.
- [x] Integrate Audio with the VGA based Game.
- [x] Play separate notes for each tile that is being intercepted.
